language: rust

addons:
  apt:
    packages:
      - p7zip-full

cache: cargo

install:
  - rustup component add rustfmt-preview
  - rustfmt --version

before_script:
  - mkdir tests
  - cd tests

  - wget https://github.com/WrinklyNinja/testing-plugins/archive/1.4.1.tar.gz
  - tar -xf 1.4.1.tar.gz
  - mv testing-plugins-1.4.1 testing-plugins

  - wget https://github.com/loot/loot-api/releases/download/0.13.8/loot_api-0.13.8-0-g47797cc_dev-win32.7z
  - 7z x loot_api-0.13.8-0-g47797cc_dev-win32.7z
  - mv loot_api-0.13.8-0-g47797cc_dev-win32 loot_api_win32

  - wget https://github.com/loot/loot-api/releases/download/0.13.8/loot_api-0.13.8-0-g47797cc_dev-win64.7z
  - 7z x loot_api-0.13.8-0-g47797cc_dev-win64.7z
  - mv loot_api-0.13.8-0-g47797cc_dev-win64 loot_api_win64

  - wget https://7-zip.org/a/7z1805-extra.7z
  - 7z x 7z1805-extra.7z -o7z

  - cd ..

script:
  - cargo fmt --all -- --check
  - cargo test --all --all-features

  # Need to rebuild the FFI wrapper so that its binary is given a filename
  # without a hash.
  - cargo build --manifest-path ffi/Cargo.toml --features ffi-headers
  - mkdir ffi/build
  - cd ffi/build
  - cmake ..
  - make
  - make test
