dist: bionic
language: rust

addons:
  apt:
    packages:
      - p7zip-full
      # tarpaulin dependencies
      - libssl-dev

cache: cargo

install:
  - rustup component add rustfmt
  - rustfmt --version
  - curl -sL https://github.com/xd009642/tarpaulin/releases/download/0.14.2/cargo-tarpaulin-0.14.2-travis.tar.gz | tar xvz -C $HOME/.cargo/bin

before_script:
  - cd tests

  - wget https://github.com/WrinklyNinja/testing-plugins/archive/1.4.1.tar.gz
  - tar -xf 1.4.1.tar.gz
  - mv testing-plugins-1.4.1 testing-plugins

  - wget https://github.com/loot/loot-api/releases/download/0.13.8/loot_api-0.13.8-0-g47797cc_dev-win32.7z
  - 7z x loot_api-0.13.8-0-g47797cc_dev-win32.7z
  - mv loot_api-0.13.8-0-g47797cc_dev-win32 loot_api_win32

  - wget https://github.com/loot/loot-api/releases/download/0.13.8/loot_api-0.13.8-0-g47797cc_dev-win64.7z
  - 7z x loot_api-0.13.8-0-g47797cc_dev-win64.7z
  - mv loot_api-0.13.8-0-g47797cc_dev-win64 loot_api_win64

  - wget https://github.com/loot/loot-api-python/releases/download/4.0.2/loot_api_python-4.0.2-0-gd356ac2_master-python2.7-win32.7z
  - 7z x loot_api_python-4.0.2-0-gd356ac2_master-python2.7-win32.7z
  - mv loot_api_python-4.0.2-0-gd356ac2_master-python2.7-win32 loot_api_python

  - wget https://7-zip.org/a/7z1805-extra.7z
  - 7z x 7z1805-extra.7z -o7z

  - cd ..

script:
  - cargo fmt --all -- --check
  - cargo test --all --all-features

  # Running cbindgen through tarpaulin fails due to an unexpected "metadata"
  # argument when generating the C header file, so skip the ffi-headers feature.
  - cargo tarpaulin --all --ciserver travis-ci --coveralls $TRAVIS_JOB_ID

  # Need to rebuild the FFI wrapper so that its binary is given a filename
  # without a hash.
  - cargo build --manifest-path ffi/Cargo.toml --features ffi-headers
  - mkdir ffi/build
  - cd ffi/build
  - cmake ..
  - make
  - make test
