os: Visual Studio 2017

version: "{build}-{branch}"

cache:
  - C:\Users\appveyor\.cargo
  - target

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - rustc -vV
  - cargo -vV

  - rustup component add rustfmt-preview
  - rustfmt --version

  - ps: mkdir tests
  - cd tests

  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/WrinklyNinja/testing-plugins/archive/1.4.0.zip', "$PWD/1.4.0.zip")
  - 7z x 1.4.0.zip
  - mv testing-plugins-1.4.0 testing-plugins

  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/loot/loot-api/releases/download/0.13.8/loot_api-0.13.8-0-g47797cc_dev-win32.7z', "$PWD/loot_api_win32.7z")
  - 7z x loot_api_win32.7z
  - mv loot_api-0.13.8-0-g47797cc_dev-win32 loot_api_win32

  - ps: (New-Object Net.WebClient).DownloadFile('https://github.com/loot/loot-api/releases/download/0.13.8/loot_api-0.13.8-0-g47797cc_dev-win64.7z', "$PWD/loot_api_win64.7z")
  - 7z x loot_api_win64.7z
  - mv loot_api-0.13.8-0-g47797cc_dev-win64 loot_api_win64

  - cd ..

build: false

test_script:
  - cargo fmt --all -- --check
  - cargo test --all --all-features

  # Need to rebuild the FFI wrapper so that its binary is given a filename
  # without a hash.
  - cargo build --manifest-path ffi/Cargo.toml --features ffi-headers
  - ps: mkdir ffi/build
  - cd ffi/build
  - cmake .. -G "Visual Studio 15 2017 Win64"
  - cmake --build .
  - ctest
